config/routes.rb
Rails.application.routes.draw do

  get 'admin/test_scripts/:id', to: 'test_scripts#show', defaults: { format: 'docx' }
  devise_for :reviewers
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    resources :questions, only: [:edit, :update]
  end
  authenticate :reviewer do
    resources :reviews, only: [:edit, :update]
  end

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :ecdl_module
  has_many :skillsets

  def has_reviews?
    self.skillsets.each do |skillset|
      if (skillset.has_reviews?)
        return true
      end
    end
    return false
  end


end

app/models/ecdl_module.rb
class EcdlModule < ActiveRecord::Base
  has_many :categories


  def has_reviews?
    self.categories.each do |category|
      if (category.has_reviews?)
        return true
      end
    end
    return false
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  after_create :add_review
  before_destroy :find_review
  after_destroy :destroy_orphaned_review

  belongs_to :task_item
  belongs_to :review
  belongs_to :syllabus_item
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers,
    :allow_destroy => true,
    :reject_if     => proc { |answers| answers['text'].blank? && answers['image'].blank? }

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :task_item, presence: true

  def add_review
    @review = Review.new(:question => self, :status => :idle)
    @review.save
    self.review = @review
  end


  def find_review
    @review = self.review
  end

  def destroy_orphaned_review
    @review.destroy
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_one :question
  belongs_to :user
  enum status: [ :idle, :being_scripted, :being_reviewed, :passed ]
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
	attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
end

app/models/skillset.rb
class Skillset < ActiveRecord::Base
  belongs_to :category
  has_many :task_items

  def has_reviews?
    self.task_items.each do |task_item|
      if (task_item.has_reviews?)
        return true
      end
    end
    return false
  end


end

app/models/syllabus_item.rb
class SyllabusItem < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :test_scripts, dependent: :destroy
  accepts_nested_attributes_for :questions,
    :reject_if     => :all_blank
  accepts_nested_attributes_for :test_scripts,
    :reject_if     => :all_blank
end

app/models/task_item.rb
class TaskItem < ActiveRecord::Base
  belongs_to :skillset
  has_many :questions

  def absolute_ref
    return self.skillset.category.ecdl_module.module_ref.to_s() + "." +
      self.skillset.category.category_ref.to_s() + "." +
      self.skillset.skillset_ref.to_s() + "." +
      self.task_item_ref.to_s
  end
end

app/models/test_script.rb
class TestScript < ActiveRecord::Base
  belongs_to :syllabus_item
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.gauth_enabled == "1"
        render "user_dashboard"
      else
        redirect_to user_displayqr_path
      end
    end
    if reviewer_signed_in?
      if current_reviewer.gauth_enabled == "1"
        render "reviewer_dashboard"
      else
        redirect_to reviewer_displayqr_path
      end
    end
    if admin_user_signed_in?
      redirect_to admin_root_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base

  def update
    @question = Question.find(params[:id])
    # should probably add logic here to ensure that question's haven't passed review
    if @question.update_attributes(question_params)
      @review = @question.review
      if @review.update_attributes(:status => :being_reviewed, :user => current_user)
        redirect_to root_path, notice: 'Question submitted successfully'
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  private

    def question_params
      params.require(:question).permit(:question_id, :stem, :image, :task_item_id, :practical, answers_attributes:[:id, :text, :correct, :image, :question_id, :_destroy])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_question(question)
    (4-question.answers.length).times { question.answers.build }
    question
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/views/questions/_answer.html.erb
<div class="answer">
  <%= form.fields_for :answer do |f| %>
    <div class="field">
      <%= f.label :answer_id %><br>
      <%= f.number_field :answer_id %>
    </div>
    <div class="field">
      <%= f.label :ans_text %><br>
      <%= f.text_field :ans_text %>
    </div>
  <% end %>
</div>

app/views/questions/_form.html.erb
<%= form_for(setup_question(@question)) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="question-display">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">New Question</h3>
      </div>
      <div class="panel-body">
        <ol class="breadcrumb">
          <li><%= @question.task_item.skillset.category.ecdl_module.name %></li>
          <li><%= @question.task_item.skillset.category.name %></li>
          <li><%= @question.task_item.skillset.name %></li>
          <li class="active"><%= @question.task_item.name %></li>
        </ol>
        <div class="row question-meta">
          <div class="col-md-4 col-md-offset-4">
            <div class="input-group">
              <span class="input-group-addon">Theoretical: </span>
              <span class="input-group-addon">
                <%= f.radio_button :practical, false , :checked => true , :value => false %>
              </span>
              <span class="input-group-addon">Practical: </span>
              <span class="input-group-addon">
                <%= f.radio_button :practical, true, :value => true %>
              </span>
            </div>
          </div>
        </div>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">Stem: </span>
          <%= f.text_field :stem, :class => "form-control" %>
        </div>
        <%= f.file_field :image %>

        <div class="panel-top-pad"></div>

        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Correct Answer:</h3>
          </div>
          <div class="panel-body">
            <div class="panel-top-pad"></div>
            <%= f.fields_for :answers, @question.answers.first do |ff| %>
              <%= ff.hidden_field :correct, :value => true %>
              <div class="field">
                <%= ff.text_field :text, :class => "form-control" %>
              </div>
              <div class="field">
                <%= ff.file_field :image %>
              </div>
              <% if ff.object.persisted? %>
                <%= ff.label :_destroy, "Destroy" %>
                <%= ff.check_box :_destroy %>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">Incorrect Answers:</h3>
          </div>
          <div class="panel-body">
            <div class="panel-top-pad"></div>
            <%= f.fields_for :answers, @question.answers[1..-1] do |ff| %>
              <%= ff.hidden_field :correct, :value => false %>
              <div>
                <div class="field">
                  <%= ff.text_field :text, :class => "form-control" %>
                </div>
                <div class="field">
                  <%= ff.file_field :image %>
                </div>
                <% if ff.object.persisted? %>
                  <%= ff.label :_destroy, "Destroy" %>
                  <%= ff.check_box :_destroy %>
                <% end %>
              </div>
              <div class="panel-top-pad"></div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="actions">
        <%= f.submit 'Submit Question', :class => 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/questions/_show.html.erb
<div class="stem-image-container">
  <div class="panel-top-pad"></div>
  <div class="question-image-container">
    <% if question.image.present? %>
      <%= image_tag question.image.url, :size => "100x100" %>
    <% end %>
  </div>
  <div class="question-stem-container">
    <%= question.stem %>
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Correct Answer:</h3>
  </div>
  <div class="panel-body">
    <% if  question.answers.first.image.present? %>
      <%= image_tag question.answers.first.image.url, :size => "100x100" %>
    <% end %>
    <%= question.answers.first.text %>
  </div>
</div>
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Incorrect Answers:</h3>
  </div>
  <div class="panel-body">
    <div class="panel-top-pad"></div>
    <% question.answers[1..-1].each do |answer| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="question-image-container">
            <% if  answer.image.present? %>
              <%= image_tag answer.image.url, :size => "100x100" %>
            <% end %>
          </div>
          <div class="question-stem-container">
            <%= answer.text %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<% if !@question.review.idle? %>
  <div class="well">
    Reason for failure: <%= @question.review.comment %>
  </div>
<% end %>
<%= render 'form' %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question ID</th>
      <th>Stem</th>
      <th>Image</th>
      <th>Task item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question_id %></td>
        <td><%= question.stem %></td>
        <td>
          <% if question.image.present? %>
            <%= image_tag question.image.url, :size => "50x50" %>
          <% else %>
            No image provided
          <% end %>
        </td>
        <td><%= question.task_item %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<%= render 'show', :question => @question %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>