config/routes.rb
Rails.application.routes.draw do

  get 'admin/test_scripts/:id', to: 'test_scripts#show', defaults: { format: 'docx' }
  devise_for :reviewers
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    resources :questions, only: [:edit, :update]
  end
  authenticate :reviewer do
    resources :reviews, only: [:edit, :update]
  end

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :ecdl_module
  has_many :skillsets

  def has_reviews?
    self.skillsets.each do |skillset|
      if (skillset.has_reviews?)
        return true
      end
    end
    return false
  end


end

app/models/ecdl_module.rb
class EcdlModule < ActiveRecord::Base
  has_many :categories


  def has_reviews?
    self.categories.each do |category|
      if (category.has_reviews?)
        return true
      end
    end
    return false
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  after_create :add_review
  before_destroy :find_review
  after_destroy :destroy_orphaned_review

  belongs_to :task_item
  belongs_to :review
  belongs_to :syllabus_item
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers,
    :allow_destroy => true,
    :reject_if     => proc { |answers| answers['text'].blank? && answers['image'].blank? }

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :task_item, presence: true

  def add_review
    @review = Review.new(:question => self, :status => :idle)
    @review.save
    self.review = @review
  end


  def find_review
    @review = self.review
  end

  def destroy_orphaned_review
    @review.destroy
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_one :question
  belongs_to :user
  enum status: [ :idle, :being_scripted, :being_reviewed, :passed ]
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
	attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
end

app/models/skillset.rb
class Skillset < ActiveRecord::Base
  belongs_to :category
  has_many :task_items

  def has_reviews?
    self.task_items.each do |task_item|
      if (task_item.has_reviews?)
        return true
      end
    end
    return false
  end


end

app/models/syllabus_item.rb
class SyllabusItem < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :test_scripts, dependent: :destroy
  accepts_nested_attributes_for :questions,
    :reject_if     => :all_blank
  accepts_nested_attributes_for :test_scripts,
    :reject_if     => :all_blank
end

app/models/task_item.rb
class TaskItem < ActiveRecord::Base
  belongs_to :skillset
  has_many :questions

  def absolute_ref
    return self.skillset.category.ecdl_module.module_ref.to_s() + "." +
      self.skillset.category.category_ref.to_s() + "." +
      self.skillset.skillset_ref.to_s() + "." +
      self.task_item_ref.to_s
  end
end

app/models/test_script.rb
class TestScript < ActiveRecord::Base
  belongs_to :syllabus_item
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.gauth_enabled == "1"
        render "user_dashboard"
      else
        redirect_to user_displayqr_path
      end
    end
    if reviewer_signed_in?
      if current_reviewer.gauth_enabled == "1"
        render "reviewer_dashboard"
      else
        redirect_to reviewer_displayqr_path
      end
    end
    if admin_user_signed_in?
      redirect_to admin_root_path
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_question(question)
    (4-question.answers.length).times { question.answers.build }
    question
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/views/home/index.html.erb
<div class="head-container">
  <h1>ECDL Scripter</h1>
  <h3>User: <%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %></h3>
  <h3>Reviewer: <%= link_to "Sign In", new_reviewer_session_path %> or <%= link_to "Sign Up", new_reviewer_registration_path %></h3>
</div>

app/views/home/reviewer_dashboard.html.erb
<div class="question-display">
  <div class="panel panel-primary">
    <div class="panel-heading">Questions for Review</div>
    <div class="list-group">
      <% Review.being_reviewed.find_each do |review| %>
        <%= link_to review.question.task_item.absolute_ref, edit_review_path(review), :class => "list-group-item" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/user_dashboard.html.erb
<div class="question-display">
  <div class="panel panel-primary">
    <div class="panel-heading">Questions for Scripting</div>
    <div class="list-group">
      <% Review.all.idle.find_each do |review| %>
        <div>
          <%= link_to (review.question.task_item.absolute_ref + " " + review.question.task_item.name ),
            edit_question_path(review.question), class: "list-group-item" %>
        </div>
      <% end %>
      <% if Review.all.idle.blank? %>
        <div class="actions">There are no new question to script at the moment.</div>
      <% end %>
    </div>
  </div>
</div>

<div class="question-display">
  <div class="panel panel-primary">
    <div class="panel-heading">Questions for Rescripting</div>
    <div class="list-group">
      <% Review.where(user: current_user).being_scripted.find_each do |review| %>
        <div class="list-group-item">
          <%= link_to review.question.stem, edit_question_path(review.question) %>
          Reason: <%= review.comment %>
      </div>
      <% end %>
      <% if Review.where(user: current_user).being_scripted.blank? %>
        <div class="actions">There are no question to rescript at the moment.</div>
      <% end %>
    </div>
  </div>
</div>