config/routes.rb
Rails.application.routes.draw do

  get 'admin/test_scripts/:id', to: 'test_scripts#show', defaults: { format: 'docx' }
  devise_for :reviewers
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    resources :questions, only: [:edit, :update]
  end
  authenticate :reviewer do
    resources :reviews, only: [:edit, :update]
  end

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :ecdl_module
  has_many :skillsets

  def has_reviews?
    self.skillsets.each do |skillset|
      if (skillset.has_reviews?)
        return true
      end
    end
    return false
  end


end

app/models/ecdl_module.rb
class EcdlModule < ActiveRecord::Base
  has_many :categories


  def has_reviews?
    self.categories.each do |category|
      if (category.has_reviews?)
        return true
      end
    end
    return false
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  after_create :add_review
  before_destroy :find_review
  after_destroy :destroy_orphaned_review

  belongs_to :task_item
  belongs_to :review
  belongs_to :syllabus_item
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers,
    :allow_destroy => true,
    :reject_if     => proc { |answers| answers['text'].blank? && answers['image'].blank? }

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :task_item, presence: true

  def add_review
    @review = Review.new(:question => self, :status => :idle)
    @review.save
    self.review = @review
  end


  def find_review
    @review = self.review
  end

  def destroy_orphaned_review
    @review.destroy
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_one :question
  belongs_to :user
  enum status: [ :idle, :being_scripted, :being_reviewed, :passed ]
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
	attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
end

app/models/skillset.rb
class Skillset < ActiveRecord::Base
  belongs_to :category
  has_many :task_items

  def has_reviews?
    self.task_items.each do |task_item|
      if (task_item.has_reviews?)
        return true
      end
    end
    return false
  end


end

app/models/syllabus_item.rb
class SyllabusItem < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :test_scripts, dependent: :destroy
  accepts_nested_attributes_for :questions,
    :reject_if     => :all_blank
  accepts_nested_attributes_for :test_scripts,
    :reject_if     => :all_blank
end

app/models/task_item.rb
class TaskItem < ActiveRecord::Base
  belongs_to :skillset
  has_many :questions

  def absolute_ref
    return self.skillset.category.ecdl_module.module_ref.to_s() + "." +
      self.skillset.category.category_ref.to_s() + "." +
      self.skillset.skillset_ref.to_s() + "." +
      self.task_item_ref.to_s
  end
end

app/models/test_script.rb
class TestScript < ActiveRecord::Base
  belongs_to :syllabus_item
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :gauth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :google_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

end

app/controllers/syllabus_items_controller.rb
class SyllabusItemsController < InheritedResources::Base

  private

    def syllabus_item_params
      params.require(:syllabus_item).permit(:name)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_question(question)
    (4-question.answers.length).times { question.answers.build }
    question
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/helpers/syllabus_items_helper.rb
module SyllabusItemsHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/views/admin/syllabus_items/_form.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    for(i=0;i< <%= @syllabus_item.questions.length %> ;i++){
      $("#syllabus_item_questions_attributes_" + i + "_task_item_id").select2({
        placeholder: "Select task item"
      });
    }
  });
</script>
<%= semantic_form_for [:admin, @syllabus_item] do |f| %>
  <%= f.inputs :name %>

  <fieldset class="inputs">
    <div class="syl-input-pad">
      <%= f.semantic_fields_for :test_scripts do |h| %>
        <%= h.input :name, label: "<strong>Test Script Name:</strong>&nbsp;&nbsp;".html_safe %>
      <% end %>
    </div>
  </fieldset>

  <fieldset class="inputs">
    <table>
      <tr class="syl-pad-left">
        <td><strong>Task Item</strong></td>
        <td><strong>Practical</strong></td>
        <td><strong>In Test Script 1</strong></td>
        <td><strong>In Test Script 2</strong></td>
        <td><strong>In Test Script 3</strong></td>
        <td><strong>In Test Script 4</strong></td>
      </tr>
      <%= f.semantic_fields_for :questions do |q| %>
        <tr>
          <td><%= q.input :task_item, label: "", class: "task-item-select" %></td>
          <td><%= q.input :practical, label: "" %></td>
          <td><%= q.input :belongs_to_test_0, label: "" %></td>
          <td><%= q.input :belongs_to_test_1, label: "" %></td>
          <td><%= q.input :belongs_to_test_2, label: "" %></td>
          <td><%= q.input :belongs_to_test_3, label: "" %></td>
        </tr>
      <% end %>
    </table>
  </fieldset>

  <%= f.actions %>
<% end %>

app/views/admin/syllabus_items/_show.html.erb
<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Status</th>
      <th><%= link_to syllabus_item.test_scripts[0].name, admin_test_script_path(syllabus_item.test_scripts[0]) %></th>
      <th><%= link_to syllabus_item.test_scripts[1].name, admin_test_script_path(syllabus_item.test_scripts[1]) %></th>
      <th><%= link_to syllabus_item.test_scripts[2].name, admin_test_script_path(syllabus_item.test_scripts[2]) %></th>
      <th><%= link_to syllabus_item.test_scripts[3].name, admin_test_script_path(syllabus_item.test_scripts[3]) %></th>
    </tr>
  </thead>

  <tbody>
    <% syllabus_item.questions.each do |question| %>
      <tr>
        <td><%= link_to question.task_item.absolute_ref, admin_question_path(question) %></td>
        <td><%= link_to question.review.status, admin_review_path(question.review) %></td>
        <td><% if question.belongs_to_test_0 %>✔<% end %></td>
        <td><% if question.belongs_to_test_1 %>✔<% end %></td>
        <td><% if question.belongs_to_test_2 %>✔<% end %></td>
        <td><% if question.belongs_to_test_3 %>✔<% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/syllabus_items/_form.html.erb
<%= form_for(@syllabus_item) do |f| %>
  <% if @syllabus_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@syllabus_item.errors.count, "error") %> prohibited this syllabus_item from being saved:</h2>

      <ul>
      <% @syllabus_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syllabus_items/edit.html.erb
<h1>Editing Syllabus Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @syllabus_item %> |
<%= link_to 'Back', syllabus_items_path %>

app/views/syllabus_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Syllabus Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @syllabus_items.each do |syllabus_item| %>
      <tr>
        <td><%= syllabus_item.name %></td>
        <td><%= link_to 'Show', syllabus_item %></td>
        <td><%= link_to 'Edit', edit_syllabus_item_path(syllabus_item) %></td>
        <td><%= link_to 'Destroy', syllabus_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Syllabus item', new_syllabus_item_path %>

app/views/syllabus_items/new.html.erb
<h1>New Syllabus Item</h1>

<%= render 'form' %>

<%= link_to 'Back', syllabus_items_path %>

app/views/syllabus_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @syllabus_item.name %>
</p>

<%= link_to 'Edit', edit_syllabus_item_path(@syllabus_item) %> |
<%= link_to 'Back', syllabus_items_path %>